CREATE TABLE IF NOT EXISTS workers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  profession VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  address TEXT NOT NULL,
  password VARCHAR(255) NOT NULL,
  skills JSON NOT NULL,
  certifications JSON NOT NULL,
  experience VARCHAR(50) NOT NULL,
  description TEXT,
  profile_photo VARCHAR(255),
  portfolio_files JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE workers
ADD COLUMN profession VARCHAR(50) NOT NULL AFTER id,
ADD COLUMN skills JSON NOT NULL AFTER password,
ADD COLUMN certifications JSON NOT NULL AFTER skills,
ADD COLUMN experience VARCHAR(50) NOT NULL AFTER certifications,
ADD COLUMN description TEXT AFTER experience,
ADD COLUMN profile_photo VARCHAR(255) AFTER description,
ADD COLUMN portfolio_files JSON AFTER profile_photo,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP; 